org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.11-beta

mod_id=cobblemon
mod_name=Cobblemon
mod_license=MPL-2.0
mod_version=1.0.0-26.2-beta
mod_group_id=com.cobblemon.mod
