package com.cobblemon.mod.util

/**
 * NBT / component key names matching official Cobblemon `DataKeys`
 * (porter `14_java_classes/.../util/DataKeys.class`).
 *
 * Use these when serializing party Pokémon so keys stay aligned with official data
 * if we ever interop save formats or copy logic from decompiled classes.
 */
object DataKeys {
    const val POKEMON: String = "Pokemon"
    const val POKEMON_UUID: String = "UUID"
    const val POKEMON_SPECIES_IDENTIFIER: String = "Species"
    const val POKEMON_NICKNAME: String = "Nickname"
    const val POKEMON_FORM_ID: String = "FormId"
    const val POKEMON_LEVEL: String = "Level"
    const val POKEMON_GENDER: String = "Gender"
    const val POKEMON_EXPERIENCE: String = "Experience"
    const val POKEMON_FRIENDSHIP: String = "Friendship"
    const val POKEMON_FULLNESS: String = "Fullness"
    const val POKEMON_INTERACTION_COOLDOWN: String = "InteractionCooldown"
    const val POKEMON_IVS: String = "IVs"
    const val POKEMON_IVS_BASE: String = "BaseIVs"
    const val POKEMON_IVS_HYPERTRAINED: String = "HyperTrainedIVs"
    const val POKEMON_EVS: String = "EVs"
    const val POKEMON_HEALTH: String = "Health"
    const val POKEMON_SCALE_MODIFIER: String = "ScaleModifier"
    const val POKEMON_MOVESET: String = "MoveSet"
    const val POKEMON_MOVESET_MOVENAME: String = "MoveName"
    const val POKEMON_MOVESET_MOVEPP: String = "MovePP"
    const val POKEMON_MOVESET_RAISED_PP_STAGES: String = "RaisedPPStages"
    const val POKEMON_ABILITY: String = "Ability"
    const val POKEMON_ABILITY_NAME: String = "AbilityName"
    const val POKEMON_ABILITY_FORCED: String = "AbilityForced"
    const val POKEMON_ABILITY_INDEX: String = "AbilityIndex"
    const val POKEMON_ABILITY_PRIORITY: String = "AbilityPriority"
    const val POKEMON_SHINY: String = "Shiny"
    const val POKEMON_STATUS: String = "Status"
    const val POKEMON_STATUS_NAME: String = "StatusName"
    const val POKEMON_STATUS_TIMER: String = "StatusTimer"
    const val POKEMON_CAUGHT_BALL: String = "CaughtBall"
    const val POKEMON_FAINTED_TIMER: String = "FaintedTimer"
    const val POKEMON_HEALING_TIMER: String = "HealingTimer"
    const val POKEMON_DATA: String = "PokemonData"
    const val POKEMON_NATURE: String = "Nature"
    const val POKEMON_MINTED_NATURE: String = "MintedNature"
    const val HELD_ITEM: String = "HeldItem"
    const val HELD_ITEM_VISIBLE: String = "HeldItemVisible"
    const val HELD_ITEM_AI_DROPPABLE: String = "HeldItemAIDroppable"
    const val POKEMON_TERA_TYPE: String = "TeraType"
    const val POKEMON_DMAX_LEVEL: String = "DmaxLevel"
    const val POKEMON_GMAX_FACTOR: String = "GmaxFactor"
    const val POKEMON_TRADEABLE: String = "Tradeable"
    const val POKEMON_FORCED_ASPECTS: String = "ForcedAspects"
    const val POKEMON_COSMETIC_ITEM: String = "CosmeticItem"
    const val POKEMON_ACTIVE_MARK: String = "ActiveMark"
    const val POKEMON_MARKS: String = "Marks"
    const val POKEMON_POTENTIAL_MARKS: String = "PotentialMarks"
    const val POKEMON_MARKINGS: String = "Markings"
    const val POKEMON_RIDE_BOOSTS: String = "RideBoosts"
    const val POKEMON_RIDE_STAMINA: String = "RideStamina"
    const val POKEMON_MIN_PERFECT_IVS: String = "MinPerfectIVs"
    const val POKEMON_STATE: String = "State"
    const val POKEMON_STATE_TYPE: String = "StateType"
    const val POKEMON_STATE_SHOULDER: String = "Shoulder"
    const val POKEMON_STATE_ID: String = "StateId"
    const val POKEMON_STATE_PLAYER_UUID: String = "StatePlayerUUID"
    const val POKEMON_STATE_POKEMON_UUID: String = "StatePokemonUUID"
    const val POKEMON_BATTLE_ID: String = "BattleId"
    const val POKEMON_POSE_TYPE: String = "PoseType"
    const val POKEMON_BEHAVIOUR_FLAGS: String = "BehaviourFlags"
    const val POKEMON_OWNER_ID: String = "OwnerId"
    const val POKEMON_HIDE_LABEL: String = "HideLabel"
    const val POKEMON_UNBATTLEABLE: String = "Unbattleable"
    const val POKEMON_COUNTS_TOWARDS_SPAWN_CAP: String = "CountsTowardsSpawnCap"
    const val POKEMON_FREEZE_FRAME: String = "FreezeFrame"
    const val POKEMON_RECALCULATE_POSE: String = "RecalculatePose"
    const val POKEMON_PLATFORM_TYPE: String = "PlatformType"
    const val POKEMON_ORIGINAL_TRAINER: String = "OriginalTrainer"
    const val POKEMON_ORIGINAL_TRAINER_NAME: String = "OriginalTrainerName"
    const val POKEMON_ORIGINAL_TRAINER_TYPE: String = "OriginalTrainerType"
    const val POKEMON_PROPERTIES_MOVES: String = "Moves"
    const val POKEMON_PROPERTIES_HELDITEM: String = "HeldItem"
    const val POKEMON_ENTITY_MOCK: String = "Mock"
    const val POKEMON_ENTITY_SCALE: String = "Scale"
    const val POKEMON_EVOLUTIONS: String = "Evolutions"
    const val BENCHED_MOVES: String = "BenchedMoves"
    const val PC_ID: String = "PCId"
    const val STORE_SLOT: String = "Slot"
    const val STORE_SLOT_COUNT: String = "SlotCount"
    const val STORE_BOX: String = "Box"
    const val STORE_BOX_NAME: String = "BoxName"
    const val STORE_BOX_WALLPAPER: String = "BoxWallpaper"
    const val STORE_BOX_COUNT: String = "BoxCount"
    const val STORE_BOX_COUNT_LOCKED: String = "BoxCountLocked"
    const val STORE_BACKUP: String = "Backup"
    const val STORE_UNLOCKED_WALLPAPERS: String = "UnlockedWallpapers"
    const val STORE_UNSEEN_WALLPAPERS: String = "UnseenWallpapers"
    const val POKEDEX_TYPE: String = "PokedexType"
    const val NUM_ENCOUNTED_WILD: String = "NumEncounteredWild"
    const val NUM_ENCOUNTED_BATTLE: String = "NumEncounteredBattle"
    const val NUM_CAUGHT: String = "NumCaught"
}
