package com.cobblemon.mod.content;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import com.cobblemon.mod.Cobblemon;

/**
 * Loads Cobblemon-imported content IDs from {@code data/cobblemon/content/*.txt}
 * (generated by {@code tools/import_porter_all.js}).
 */
public final class ContentLists {
    private static final List<String> ITEMS = load("data/cobblemon/content/item_ids.txt");
    private static final List<String> BLOCKS = load("data/cobblemon/content/block_ids.txt");

    private ContentLists() {}

    public static List<String> items() {
        return ITEMS;
    }

    public static List<String> blocks() {
        return BLOCKS;
    }

    private static List<String> load(String classpathPath) {
        List<String> out = new ArrayList<>();
        // Try leading slash and without (both classloader styles)
        var in = ContentLists.class.getClassLoader().getResourceAsStream(classpathPath);
        if (in == null) {
            in = ContentLists.class.getResourceAsStream("/" + classpathPath);
        }
        if (in == null) {
            Cobblemon.LOGGER.warn("Content list missing on classpath: {} — run node tools/import_porter_all.js", classpathPath);
            return Collections.emptyList();
        }
        try (var reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) {
                    continue;
                }
                // path-safe ids only
                if (line.matches("[a-z0-9_./-]+")) {
                    out.add(line);
                }
            }
        } catch (Exception e) {
            Cobblemon.LOGGER.error("Failed loading content list {}", classpathPath, e);
        }
        return Collections.unmodifiableList(out);
    }
}
